name: app
description: Flutter project for view and subscribe in trip.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  core_sdk:
#    git:
#      url: https://github.com/khaledAlHalawa/flutter-core-utils.git
#      ref: master


  # other
  tuple: ^2.0.0
  json_annotation: ^4.6.0
  freezed_annotation: ^2.1.0
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  dartz: ^0.10.1
  logger: ^1.1.0
  adaptive_breakpoints: ^0.1.4
  animations: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  path: ^1.8.1
  numeral: ^2.0.1
  infinite_scroll_pagination: ^3.2.0
  device_preview: ^1.1.0
  location: ^4.4.0
  permission_handler: ^10.0.0


  # CLIENT
  dio: ^4.0.6


  # STATE MANAGEMENT
  flutter_mobx: ^2.0.4
  mobx: ^2.0.7+5
  flutter_riverpod: ^1.0.3


  # DI
  get_it: ^7.2.0
  injectable: ^1.5.3


  # UI
  cupertino_icons: ^1.0.5
  flutter_zoom_drawer: ^3.0.3
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.3
  flutter_spinkit: ^5.1.0
  shimmer: ^2.0.0
  flutter_screenutil: ^5.5.3+2
  form_field_validator: ^1.1.0
  persistent_bottom_nav_bar: ^4.0.2
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  another_xlider: ^1.1.2
  expandable: ^5.0.1
  syncfusion_flutter_datepicker: ^20.2.43
  lottie: ^1.4.1
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.1.10
  fancy_shimmer_image: ^2.0.2
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  flutter_polyline_points: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.7
  json_serializable: ^6.3.1
  injectable_generator: ^1.5.4
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  freezed: ^2.1.0+1
  mockito: ^5.3.0

flutter_icons:
  image_path: "assets/images/tripper_logo.png"
  background:
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/languages/
    - assets/svg/
    - assets/images/
    - assets/fonts/
    - assets/pin_maps/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Light.ttf